CREATE TABLE IF NOT EXISTS ads_banners (
  id VARCHAR(64) PRIMARY KEY,
  slot VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(500),
  image_url VARCHAR(500),
  link_url VARCHAR(500),
  bg_color VARCHAR(20),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  priority INT NOT NULL DEFAULT 0,
  clicks BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
