@host = http://localhost:8080

### engagement 조회 (비로그인 허용)
GET {{host}}/api/posts/1/engagement

### like 추가 (로그인 필요)
POST {{host}}/api/posts/1/like

### like 취소 (로그인 필요)
DELETE {{host}}/api/posts/1/like

### bookmark 추가 (로그인 필요)
POST {{host}}/api/posts/1/bookmark

### bookmark 취소 (로그인 필요)
DELETE {{host}}/api/posts/1/bookmark

### 좋아요 누른 사용자 목록 (비로그인 허용)
GET {{host}}/api/posts/1/likes/users?limit=20

### 내 북마크 목록 (로그인 필요)
GET {{host}}/api/posts/bookmarks/me?limit=20
