CREATE TABLE IF NOT EXISTS notification_read_state (
  user_id BIGINT PRIMARY KEY,
  last_seen_comment_id BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
