spring:
  forward-headers-strategy: framework

  profiles:
    default: ${SPRING_PROFILES_DEFAULT:dev}

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
